version: '3'

services:
  test_docker:
    build: .
    container_name: test_docker
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - leaderboard-redis

  leaderboard-redis:
    image: bitnami/redis:latest
    container_name: leaderboard-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL
    volumes:
      - leaderboard-redis-data:/data
    ports:  
      - '6379:6379'

volumes:
  leaderboard-redis-data:
